on: [push]

jobs:
  xccdf-validate:
    runs-on: ubuntu-latest
    name: Validate xccdf
    steps:
      - name: Hello world action step
        uses: mitre/xccdf-validate-action@main
        with: 
          input: sample_data/xccdf-results-openscap-rhel7.xml