on: [push]

jobs:
  xccdf-validate:
    runs-on: ubuntu-latest
    name: Validate xccdf
    steps:
      - name: Hello world action step
        uses: mitre/xccdf-validate-action@main
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
