on: [push]

jobs:
  xccdf-validate:
    runs-on: ubuntu-latest
    name: Validate xccdf
    steps:
      - uses: actions/checkout@master

      - name: Validate XCCDF File
        uses: mitre/xccdf-validate-action@v1
        with: 
          input: sample_data/xccdf-results-openscap-rhel7.xml